name: WiseCloud Prepare # Name of the Catalog Entry
description: WiseCloud Prepare stacks # Description of the Catalog Entry
version: 0.1 # Version of the Catalog to be used
category: WiseCloud Prepare # Category to be used for searching catalog entries
